### ISSUE TITLE
Multiple issues

### ISSUE THREAD

**Issue by LloydLabs** [andreais/server_deployment#10]
https://github.com/rudreais/server_deployment/blob/master/client.c#L161 - lack of error checking
https://github.com/rudreais/server_deployment/blob/master/client.c#L157 - no need for `(char*)` typecast
https://github.com/rudreais/server_deployment/blob/master/client.c#L147 - `client_socket` is never checked to of have been successfully opened
https://github.com/rudreais/server_deployment/blob/master/client.c#L98 - this should be `sizeof(buff) - 1)`
https://github.com/rudreais/server_deployment/blob/master/client.c#L99 - use the safe `strncmp` version
https://github.com/rudreais/server_deployment/blob/master/client.c#L93 - `1 * 1000` is `1000`
https://github.com/rudreais/server_deployment/blob/master/client.c#L98 - lack of error checking
https://github.com/rudreais/server_deployment/blob/master/client.c#L120 - return value will always be `NULL`, no need for a `void*` return type
https://github.com/rudreais/server_deployment/blob/master/client.c#L137 - thread is never checked to of have successfully spawned
https://github.com/rudreais/server_deployment/blob/master/client.c#L123 - method should be static
https://github.com/rudreais/server_deployment/blob/master/client.c#L77 - method should be static
https://github.com/rudreais/server_deployment/blob/master/client.c#L61-L62 - generic names, use something more specific, e.g. `SERVER_DEFAULT_ANSI`.
https://github.com/rudreais/server_deployment/blob/master/client.c#L164-L165 - no need for both calls on `client_socket`

You should think about writing your code in a more consistent style too, such as following the Linux kernel style - https://www.kernel.org/doc/html/v4.10/process/coding-style.html

**Comment by rudreais** [comment]
the fuck happened
thanks, will see your issues in the day hahaha

**Comment by rudreais** [comment]
just to precise: this project was made to learn sockets in C.

@LloydLabs 

` https://github.com/rudreais/server_deployment/blob/master/client.c#L164-L165 - no need for both calls on client_socket`
why so ? i read that shutdown doesn't close the file descriptor, so both of them are needed. mind explaining why ?

` https://github.com/rudreais/server_deployment/blob/master/client.c#L93 - 1 * 1000 is 1000` well, shame on me. i forgot to delete this one, was for tests purpose

`You should think about writing your code in a more consistent style too, such as following the Linux kernel style` yep will consider rewriting properly when working on the project again, sorry for the inconvenience.

most of the code isn't bullet proof, just because it was only to learn. it's a write-and-try code, not going to be implemented. i know it's still a bad practise, but that's how it was. however though, i'm gonna do the error parsing.

**Comment by rudreais** [comment]
` https://github.com/rudreais/server_deployment/blob/master/client.c#L120 - return value will always be NULL, no need for a void* return type` i didn't understand that part as well.

**Comment by rudreais** [comment]
as someone told me, shutdown + close is a proper way to stop a connection
https://stackoverflow.com/questions/4160347/close-vs-shutdown-socket
